### ISSUE TITLE
大哥有QQ吗直接卡死

### ISSUE THREAD

**Issue by a2853721** [jungleninja/UE4Dumper-IOS#1]
![image](https://user-images.githubusercontent.com/40255334/141291489-133dfeeb-e3c2-44e5-9f2e-98ded11eff7f.png)

**Comment by jungleninja** [comment]
Offsets.h里面的偏移自己看下，一般是ULevelToAActorsCount  ULevelToAActors这两个有问题就会卡住

**Comment by a2853721** [comment]
解决了大佬谢谢

**Comment by a2853721** [comment]
我是第一个看到的哈哈哈

**Comment by a2853721** [comment]
关注了

**Comment by tututu-patch** [comment]
第一个star的不是我么

**Comment by a2853721** [comment]
LOL国际服弄了 国服IDA啥都找不到  全网也没有IOS的动态UNITY dump工具 太难了
